from __future__ import annotations

"""scopeform up — start a full local Scopeform stack with one command.

Generates secrets, writes a compose file under ~/.scopeform/stack/, and runs
`docker compose up -d`. Everything — API, dashboard, Postgres, Redis — runs on
the developer's machine. No account, no cloud, nothing leaves the box.
"""

import base64
import os
import secrets
import shutil
import subprocess
from pathlib import Path

import typer
from rich.console import Console

console = Console()

STACK_DIR = Path.home() / ".scopeform" / "stack"

COMPOSE_TEMPLATE = """# Generated by `scopeform up`. Edit freely — regenerate with `scopeform up --reset`.
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: scopeform
      POSTGRES_USER: scopeform
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - scopeform_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scopeform -d scopeform"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/emartai/scopeform-api:latest
    environment:
      DATABASE_URL: postgresql+asyncpg://scopeform:${POSTGRES_PASSWORD}@postgres:5432/scopeform
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      API_BASE_URL: http://localhost:8000
      FRONTEND_URL: http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"

  web:
    image: ghcr.io/emartai/scopeform-web:latest
    environment:
      NEXT_PUBLIC_API_URL: http://api:8000
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  scopeform_pg:
"""


def _generate_env() -> str:
    # A Fernet key is 32 url-safe-base64 bytes — no cryptography import needed.
    fernet_key = base64.urlsafe_b64encode(os.urandom(32)).decode()
    return (
        "# Generated by `scopeform up` — keep this file private.\n"
        f"JWT_SECRET={secrets.token_hex(32)}\n"
        f"ENCRYPTION_KEY={fernet_key}\n"
        f"POSTGRES_PASSWORD={secrets.token_urlsafe(24)}\n"
    )


def _compose_binary() -> list[str] | None:
    if shutil.which("docker") is None:
        return None
    probe = subprocess.run(
        ["docker", "compose", "version"], capture_output=True, text=True, check=False
    )
    return ["docker", "compose"] if probe.returncode == 0 else None


def _run_compose(args: list[str]) -> int:
    compose = _compose_binary()
    if compose is None:
        console.print(
            "[bold red]Docker (with the compose plugin) is required.[/bold red]\n"
            "Install it from https://docs.docker.com/get-docker/ — or clone the repo "
            "and run the stack manually (see the Self-hosting section of the README)."
        )
        raise typer.Exit(code=2)
    return subprocess.run(
        [*compose, "-f", str(STACK_DIR / "docker-compose.yml"), *args],
        cwd=STACK_DIR,
        check=False,
    ).returncode


def up_command(
    stop: bool = typer.Option(False, "--stop", help="Stop the local stack instead of starting it."),
    reset: bool = typer.Option(False, "--reset", help="Regenerate the compose file (keeps your .env secrets)."),
) -> None:
    """Start (or stop) a full local Scopeform stack — API, dashboard, Postgres, Redis."""
    STACK_DIR.mkdir(parents=True, exist_ok=True)
    compose_path = STACK_DIR / "docker-compose.yml"
    env_path = STACK_DIR / ".env"

    if stop:
        code = _run_compose(["down"])
        if code == 0:
            console.print("[green]✓ Scopeform stack stopped.[/green]")
        raise typer.Exit(code=code)

    if reset or not compose_path.exists():
        compose_path.write_text(COMPOSE_TEMPLATE, encoding="utf-8")
    if not env_path.exists():
        env_path.write_text(_generate_env(), encoding="utf-8")
        os.chmod(env_path, 0o600)
        console.print(f"Generated secrets at [cyan]{env_path}[/cyan] (kept locally, chmod 600).")

    console.print("Starting the Scopeform stack (API, dashboard, Postgres, Redis)...")
    code = _run_compose(["up", "-d", "--wait"])
    if code != 0:
        console.print(
            "[bold red]docker compose failed.[/bold red] "
            f"Inspect with: docker compose -f {compose_path} logs"
        )
        raise typer.Exit(code=code)

    console.print("\n[green]✓ Scopeform is running — fully local.[/green]")
    console.print("  Dashboard:  [cyan]http://localhost:3000[/cyan]")
    console.print("  API:        [cyan]http://localhost:8000[/cyan]")
    console.print("\nNext steps:")
    console.print("  1. Open the dashboard and create your account (stored in YOUR database)")
    console.print("  2. [cyan]scopeform login[/cyan]")
    console.print("  3. [cyan]scopeform init[/cyan] in your agent repo, then [cyan]scopeform deploy[/cyan]")
    console.print("\nStop anytime with [cyan]scopeform up --stop[/cyan]")
